server:
  port: 8081
  
spring:
  application:
    name: USUARIO-SERVICE
  config:
    import: configserver:http://localhost:8085
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    
management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health
 
    endpoint:
      health:
        show-details: always
 
 
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        
    retry:
      instances:
        ratingHotelService:
          max-attempts: 3
          wait-duration: 5s