server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
     
  application:
    name: USUARIO-SERVICE 

  config:
    import: configserver:http://localhost:8085
  profiles:
    active: prod