server:
  port: 8083

spring:
  application:
    name: CALIFICACION-SERVICE
  config:
    import: configserver:http://localhost:8085
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservicios
